name: Build redis
on: [push, pull_request]
jobs:
  run:
    name: Build
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [macos-latest, ubuntu-latest, windows-latest]
        ocaml-version: ["4.05.0"]
    steps:
      - uses: actions/checkout@master
      - uses: avsm/setup-ocaml@master
        with:
          ocaml-version: ${{ matrix.ocaml-version }}
      - run: opam pin -n .
      - run: opam install -t . --deps-only
      - run: opam exec -- dune build
      - name: Start containers
        run: docker compose up -d
        if: ${{ matrix.operating-system  == 'ubuntu-latest'}}
      - run: opam exec -- dune runtest
        if: ${{ matrix.operating-system  == 'ubuntu-latest'}}
      - name: Stop containers
        run: docker compose down
        if: ${{ matrix.operating-system  == 'ubuntu-latest'}}
